package org.vaadin.backend;

import org.apache.deltaspike.data.api.EntityRepository;
import org.apache.deltaspike.data.api.Repository;
import org.vaadin.backend.domain.Customer;

/**
 * An implementation of this repository is auto-generated by DeltaSpike Data
 * library. This way we can save ourselves from writing lots of basic (but 
 * error prone) JPA boilerplate code.
 * 
 * For more information about DeltaSpike Data, see:
 * https://jaxenter.com/top-3-jpa-productivity-boosters-for-java-ee-developers-deltaspike-data-116136.html
 */
@Repository(forEntity = Customer.class)
public interface ContactRepository extends EntityRepository<Customer, Long> {

}